#
# Copyright 2024, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Include this snippet in your project Makefile to build
# the IMX8MQ iomuxc driver
#
# NOTES
#  Generates iomuxc_driver.elf
#  Requires libsddf_util_debug.a in ${LIBS} (MAYBE)? 
#  Has X parameters: TODO
#  Needs three variables set in system description file:
#  i2c_bus --- the i2c controller
#  gpio --- the GPIO registers for the pinmux
#  clk --- the clock registers

