
/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 ** SPDX-License-Identifier: BSD-2-Clause
 */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#pragma once

enum sel4_arch_invocation_label {
    X86PDPTMap = nInvocationLabels,
    X86PDPTUnmap,
#if defined(CONFIG_X86_64_VTX_64BIT_GUESTS)
    X86VCPUReadMSR,
#endif
#if defined(CONFIG_X86_64_VTX_64BIT_GUESTS)
    X86VCPUWriteMSR,
#endif
    nSeL4ArchInvocationLabels
};