[package]
name = "sdmmc_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4-microkit = { git = "https://github.com/seL4/rust-sel4.git", rev = "5826be1a6c83803faeaa79cd9f164c26a5a32e7c" }
sdmmc_hal = { path = "sdmmc_hal/meson" }
sdmmc_protocol = { path = "sdmmc_protocol", features = ["sel4-microkit"] }

[build]
build = "build.rs"