# Copyright 2024, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to *only* run on GitHub pull requests

name: PR

on: [pull_request]

jobs:
  whitespace:
    name: 'Trailing Whitespace'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/git-diff-check@master

  style:
    name: Style
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        run: |
          curl https://raw.githubusercontent.com/seL4/ci-actions/master/scripts/checkout.sh | bash
          curl https://raw.githubusercontent.com/seL4/ci-actions/master/scripts/fetch-base.sh | bash
          # This creates a "test-revision" rev in the git repo.
          # Print this out for visibility.
          git rev-parse test-revision

      - name: Install clang-format-19
        run: |
          DISTRO_CODE='noble'

          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository -u "deb http://apt.llvm.org/${DISTRO_CODE}/ llvm-toolchain-${DISTRO_CODE} main"

          sudo apt-get install clang-format-20

          clang-format-20 --version

      - name: Check formatting
        run: |
          git clang-format-20 --binary 'clang-format-20' \
            --diff ${GITHUB_BASE_REF} test-revision --verbose \
          || (
            echo "::error::Has your style check failed? Go to sddf/ci/README to learn more"
            exit 1
          )
